# Generated by Django 4.2 on 2023-05-04 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 17, 53, 23, 190016), null=True),
        ),
    ]
