# Generated by Django 4.2 on 2023-05-05 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_article_title_image_link_article_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 35, 34, 398112), null=True),
        ),
    ]
